[General]
EnableNetworkConfiguration=false
ControlPortOverNL80211=true
DisableCoalescing=true

[Scan]
DisablePeriodicScan=false
RoamThreshold=-75
RoamThreshold5G=-80

[Network]
EnableIPv6=false
RoutePriorityOffset=300