general {
    lock_cmd = /home/mocicu/.config/quickshell/lock.sh
    before_sleep_cmd = /home/mocicu/.config/quickshell/lock.sh && sleep 3
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 300 # 5mins
    on-timeout = /home/mocicu/.config/quickshell/lock.sh
}

listener {
    timeout = 600 # 10mins
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 900 # 15mins
    on-timeout = systemctl suspend || loginctl suspend
}
